### ISSUE TITLE
Error in mohsin/txt/humans

### ISSUE THREAD

**Issue by drtzack** [SaifurRahmanMohsin/Txt#2]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'information' in 'order clause' (SQL: select `mohsin_txt_humans`.* from `mohsin_txt_humans` order by `information` asc limit 20 offset 0)

**Comment by SaifurRahmanMohsin** [comment]
This issue was resolved on the last commit. Please update your plugin and check if it persists. If it does kindly make a comment below describing the order of steps required to reproduce this issue and if possible screenshots

**Comment by SaifurRahmanMohsin** [comment]
This issue is the same as issue #1 and it has indeed be resolved couple of hours ago. I've made a commit now to improve how the information field is shown in the column list and also added seeding data to agents table with a version bump in the plugin.

Please update the plugin in your backend and do let me know if the issue (or any other issue) persists. I'm closing this issue now. Thanks for your insights. Feel free to leave a review or suggestions in the plugin page if you like the plugin. Enjoy!

**Comment by drtzack** [comment]
It's still crashing when clicking information or directives to sort them.

**Comment by Silarn** [comment]
I'm seeing the same thing. Sorting appears to totally break things. I'm no expert in Laravel/October, but in glancing through the documentation I don't see anything wrong with the setup. So it seems like a larger bug, unless there's separate relationship setup for the sorting functions somewhere.

**Comment by Silarn** [comment]
To specify, the initial view looks fine, but as soon as you sort, things break - and it's trying to load the information column without joining the two tables. Unfortunately, this sort is cached in the browser, so this breaks viewing the page altogether if you reload the view.

**Comment by SaifurRahmanMohsin** [comment]
I couldn't recreate the issue in my end. Ultimately @drtzack removed the column entirely in his October install by removing
```
information:
    label: Information
```
in [this file](../blob/master/models/human/columns.yaml)

Removing this doesn't break the plugin's original functionality. You won't be able to see the information column in the Humans view controller, that's it!

If you do find the crux of the problem feel free to make a PR and i'll add that after testing if it's a valid solution. I used the October scaffolding commands to generate the controller so the issue must probably be in RC of OctoberCMS rather than the plugin itself. Thanks for using Txt

**Comment by Silarn** [comment]
I'm tending to agree - this seems like a bug in October or maybe Laravel - possibly with today's code update.

As long as you don't try to sort the columns, there's no problem. If you clear your browser cache and refrain from trying to sort the columns, it's alright. No need to remove the column, which nice to have...

**Comment by SaifurRahmanMohsin** [comment]
That's the only reason i haven't removed it. I am considering removing the sorting alone until October is more stable. That way the plugin will not break and will be stable.

**Comment by SaifurRahmanMohsin** [comment]
I am closing this issue. Kindly comment back if you still face this issue. I have not received any new reports on such an issue and believe that it has been patched in recent October updates. If you face this issue still, kindly comment with as much information as possible so that I can help you to resolve it.
